

module.exports = (sequelize, Sequelize) => {
    const Equipment = sequelize.define("pg_equipment", {
        id:{
          //  type: Sequelize.UUID,
            type: Sequelize.STRING,
            primaryKey: true,
            allowNull: false,
           // defaultValue: Sequelize.UUIDV4
        },
        equipment:{
            type: Sequelize.STRING
        },
        userstatus:{
            type:Sequelize.STRING
        },
        room:{
            type:Sequelize.STRING
        },
        equipmentdescription:{
            type:Sequelize.STRING
        },
        storagelocation:{
            type:Sequelize.STRING
        },
        salesorder:{
            type:Sequelize.STRING
        },
        plant:{
            type:Sequelize.STRING
        },
        maintenanceplant:{
            type:Sequelize.STRING
        },
        material:{
            type:Sequelize.STRING
        },
        createdon:{
            type:Sequelize.STRING
        },
        modifiedon:{
            type:Sequelize.STRING
        },
        systemstatus:{
            type:Sequelize.STRING
        },
        modelnumber:{
            type:Sequelize.STRING
        },
        superordequip:{
            type:Sequelize.STRING
        },
        asset:{
            type:Sequelize.STRING
        },
        subnumber:{
            type:Sequelize.STRING
        },
        workcenter:{
            type:Sequelize.STRING
        },
        equipmentcategory:{
            type:Sequelize.STRING
        },
        objecttype:{
            type:Sequelize.STRING
        },
        mainworkcenter:{
            type:Sequelize.STRING
        },
        costcenter:{
            type:Sequelize.STRING
        },
        materialdescription:{
            type:Sequelize.STRING
        },
        techidnumber:{
            type:Sequelize.STRING
        },
        gpslocation:{
            type:Sequelize.STRING
        },
        sortfield:{
            type:Sequelize.STRING
        },
        roomdescription:{
            type:Sequelize.STRING
        },
        region:{
            type:Sequelize.STRING
        },
        division:{
            type:Sequelize.STRING
        },
        functionalloc:{
            type:Sequelize.STRING
        },
        inventoryno:{
            type:Sequelize.STRING
        },
        sizedimens:{
            type:Sequelize.STRING
        },
        sizgrossweightedimens:{
            type:Sequelize.STRING
        },
        weightunit:{
            type:Sequelize.STRING
        },
        startupdate:{
            type:Sequelize.STRING
        },
        acquisitiondate:{
            type:Sequelize.STRING
        },
        deliverydate:{
            type:Sequelize.STRING
        },
        batch:{
            type:Sequelize.STRING
        },
        countryofmanufacture:{
            type:Sequelize.STRING
        },
        currentcustomer:{
            type:Sequelize.STRING
        },
        customerwarrantydesc:{
            type:Sequelize.STRING
        },
        vendorwarrantydesc:{
            type:Sequelize.STRING
        },
        endcustomer:{
            type:Sequelize.STRING
        },
        manufactureserialnumber:{
            type:Sequelize.STRING
        },
        manufacturerofasset:{
            type:Sequelize.STRING
        },
        manufacturerpartnumber:{
            type:Sequelize.STRING
        },
        objectnumber:{
            type:Sequelize.STRING
        },
        sapoperator:{
            type:Sequelize.STRING
        },
        salesorganization:{
            type:Sequelize.STRING
        },
        telephone:{
            type:Sequelize.STRING
        },
        timesgechangedby:{
            type:Sequelize.STRING
        },
        validfrom:{
            type:Sequelize.STRING
        },
        validto:{
            type:Sequelize.STRING
        },
        vendor:{
            type:Sequelize.STRING
        },
        originalroom:{
            type:Sequelize.STRING
        },
       


    });
    return Equipment;
}